### ISSUE TITLE
New dataset: A12 Neu erstellte Wohnungen

### ISSUE THREAD

**Issue by ukrcherry** [statistikZH/statbotData#18]
## Dataset properties

* URL: https://www.pxweb.bfs.admin.ch/pxweb/de/px-x-0904030000_107/-/px-x-0904030000_107.px
* format: px
* size: 0.4MB
* dimensions: grossregion / kanton / gemeinde, gebäudetyp, jahr
* units: Unzahl
* lang: de

## Additional notes

[Special processing or consideration with this dataset]

## Questions

[ Request for help / advice on how to handle this dataset. Tag people whose help would be welcome]

**Comment by sabinem** [comment]
Will not be done, since we are focusing on cantonal datasets now.
